### ISSUE TITLE
Frontend build grafana toolkit dependency not resolving

### ISSUE THREAD

**Issue by engauged** [marcusolsson/grafana-csv-datasource#2]
Hi there,

I've attempted to build the frontend for this project and it would appear that one of the dependencies is perhaps no longer available.

```yarn install
yarn install v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@grafana/toolkit/-/toolkit-6.4.0-alpha.44-2c5d1745c.tgz: Request failed \"404 Not Found\"".
```

I then attempted an upgrade via
```
yarn upgrade --dev "@grafana/toolkit"@next
```

but the compilation failed with a series of `grafana/ui` related issues

```
Compiling...  [tsl] ERROR in /Users/matbaker/dev/sandbox/grafana-csv-datasource/src/module.ts(1,10)
        TS2305: Module '"../../../../../../Users/matbaker/dev/sandbox/grafana-csv-datasource/node_modules/@grafana/ui"' has no exported member 'DataSourcePlugin'.
  [tsl] ERROR in /Users/matbaker/dev/sandbox/grafana-csv-datasource/src/CSVDataSource.ts(3,10)
        TS2305: Module '"../../../../../../Users/matbaker/dev/sandbox/grafana-csv-datasource/node_modules/@grafana/ui"' has no exported member 'DataQueryRequest'...
```

It would appear that the current combination of latest devDependencies does not compile. Is there some pinned combination of versions of the dependencies that is known to compile?

Thanks in advance for any guidance on the subject.

**Comment by mubeta06** [comment]
I believe this issue can be overcome by simply doing the following:
`yarn upgrade @grafana/toolkit && yarn install && yarn build`
